### ISSUE TITLE
Deebot 601 not working

### ISSUE THREAD

**Issue by dev-xaur** [mrbungle64/ioBroker.ecovacs-deebot#2]
I tested the adapter on my [Deebot 601](https://www.ecovacs.com/de/deebot-robotic-vacuum-cleaner/DEEBOT-600-601-605/). Connection works correctly, data (name, nick, serial, etc.) are transmitted, but the control (charge, clean, edge, spot stop) does not work. And in the log only info messages appear, but no errors.

**Comment by mrbungle64** [comment]
Thanks for your feedback :)
I'll try to enhance the error handling and to provide error messages to the log.

Do the states 'info.cleanstatus' and 'info.chargestatus' display correct information when you control the device app/manually?

**Comment by dev-xaur** [comment]
> Do the states 'info.cleanstatus' and 'info.chargestatus' display correct information when you control the device app/manually?

both states are empty, only connection and name are set. Neither the app nor the remote control changes any of the states.

**Comment by mrbungle64** [comment]
Hi @dev-xaur,

I released a new version of the adapter. I hope your device works (better) by using the new version.

**Comment by dev-xaur** [comment]
tach auch, 

unfortunately it still doesn't work, I have removed the old instance and reinstalled version 0.3.3. Starting the instance only works with at least one spot area, on startup a warning '(10954) Failure code 0002' is logged. If necessary I can provide additional logs

**Comment by mrbungle64** [comment]
> tach auch,
> 
> unfortunately it still doesn't work, I have removed the old instance and reinstalled version 0.3.3. Starting the instance only works with at least one spot area, on startup a warning '(10954) Failure code 0002' is logged. If necessary I can provide additional logs

Hi @dev-xaur,

can you please install the latest version from gitgub?
https://github.com/mrbungle64/ioBroker.ecovacs-deebot.git

I improved the logging a few minutes ago. The Deebot 601 should work.
If not please post additional logs. Thanks in advance :)

**Comment by dev-xaur** [comment]
tach auch, 

> I improved the logging a few minutes ago. The Deebot 601 should work.
> If not please post additional logs. Thanks in advance :)

here with current version from git repository, no running instances except 'ecovacs', 'admin' & 'web'

![image](https://user-images.githubusercontent.com/49554154/73596737-46abeb80-4525-11ea-95c8-81e61703c3ed.png)

or 'complete' including update
[ecovacs-log.pdf](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/files/4143064/ecovacs-log.pdf)

**Comment by mrbungle64** [comment]
> tach auch,
> 
> > I improved the logging a few minutes ago. The Deebot 601 should work.
> > If not please post additional logs. Thanks in advance :)
> 
> here with current version from git repository, no running instances except 'ecovacs', 'admin' & 'web'
> 
Thanks for providing logs.

'Couldn't reach the vac :[404] recipient-unavailable' usally means that the device is not available for the Ecovacs server.
If the message appears again please check if the device is reachable via mobile app.

Did you press all the buttons (clean, edge etc) between 18:47:15 and 18:47:22 or was this somehow triggered automatically?

**Comment by dev-xaur** [comment]
> 'Couldn't reach the vac :[404] recipient-unavailable' usally means that the device is not available for the Ecovacs server.
> If the message appears again please check if the device is reachable via mobile app.

i will try ... 

> Did you press all the buttons (clean, edge etc) between 18:47:15 and 18:47:22 or was this somehow triggered automatically?

nothing automatically triggered, when I use the APP then these actions do not appear in the log of the iobroker

**Comment by mrbungle64** [comment]
Hi @dev-xaur,

the adapter (version 0.3.4) is now available via latest repo :)

Can you please check the value in 'info.communicationProtocol'?
If the value is 'XMPP' your device should work :)

**Comment by dev-xaur** [comment]
hi @mrbungle64, 

i installed the last version from the repo and changed the value from 'info.communicationProtocol' to 'XMPP' and now the main operations work. Only 'control.pause' seems not to work and all 'consumable.*' are empty.

**Comment by mrbungle64** [comment]
> hi @mrbungle64,
> 
> i installed the version 0.3.4 from the latest repo and changed the value from 'info.communicationProtocol' to 'XMPP' and now the main operations work. Only 'control.pause' seems not to work and all 'consumable.*' are empty.

Hi @dev-xaur 

did you change the value of 'info.communicationProtocol' manually?

**Comment by dev-xaur** [comment]
> did you change the value of 'info.communicationProtocol' manually?

yes, but after installing version 0.3.9 from git, it's now back to MQTT and still works ;)

**Comment by mrbungle64** [comment]
@dev-xaur 
How about the 'info' channel (e.g. 'battery', 'chargestatus', 'cleanstatus')?

**Comment by dev-xaur** [comment]
> @dev-xaur
> Are the infos in the 'info' channel working (e.g. 'battery', 'chargestatus', 'cleanstatus')?

no information, no matter in which mode 
![image](https://user-images.githubusercontent.com/49554154/74728097-786dc380-5242-11ea-9a0c-c34efe7535a5.png)

> Btw have you installed a water tank?

no water tank installed

**Comment by mrbungle64** [comment]
@dev-xaur 

I just released version 0.3.10 on GitHub. It might be possible that the values are now displayed :)

**Comment by dev-xaur** [comment]
> @dev-xaur
> 
> It might be possible that the values are now displayed :)

correct, now the values are displayed

**Comment by mrbungle64** [comment]
Deebot 601 now seems to work to almost full extent
